#!/usr/bin/env bash
# Lumen secret-sync: read root .env and fan out values to:
#   - Config/Secrets.xcconfig  (consumed by xcodebuild → Info.plist)
#   - supabase/.env            (consumed by `supabase functions serve` and deploy)
#
# Usage: ./scripts/sync-secrets.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found. Copy .env.example to .env first." >&2
  exit 1
fi

# Read .env line-by-line so we work on macOS's bundled bash 3.2.
while IFS= read -r line; do
  case "$line" in
    ''|'#'*) continue ;;
  esac
  if [[ "$line" =~ ^([A-Z_][A-Z0-9_]*)=(.*)$ ]]; then
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    # Strip optional surrounding single or double quotes.
    val="${val%\"}"; val="${val#\"}"
    val="${val%\'}"; val="${val#\'}"
    export "$key=$val"
  fi
done < "$ENV_FILE"

require() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "warn: $name is empty in .env (continuing — fill in to enable that feature)" >&2
  fi
}

# Required for the iOS app to compile & install:
require APP_BUNDLE_PREFIX
require APP_GROUP_ID
# Required to actually talk to the backend at runtime:
require SUPABASE_URL
require SUPABASE_ANON_KEY

# ---- 1. iOS Secrets.xcconfig ------------------------------------------------
XCCONFIG="$ROOT/Config/Secrets.xcconfig"
mkdir -p "$ROOT/Config"

# xcconfig requires escaping `//` in URLs as `/$()/` so it isn't treated as a comment.
escape_xcconfig_url() {
  echo "${1//\/\///\$()/}"
}

cat > "$XCCONFIG" <<EOF
// AUTO-GENERATED by scripts/sync-secrets.sh from .env. Do not edit by hand.
// Run \`./scripts/sync-secrets.sh\` after changing .env.

SUPABASE_URL = $(escape_xcconfig_url "${SUPABASE_URL:-}")
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY:-}

APP_BUNDLE_PREFIX = ${APP_BUNDLE_PREFIX:-com.yourorg}
APPLE_TEAM_ID = ${APPLE_TEAM_ID:-}
APP_GROUP_ID = ${APP_GROUP_ID:-group.com.yourorg.lumen.shared}
EOF

echo "✓ wrote $XCCONFIG"

# ---- 2. Supabase Edge Functions .env ----------------------------------------
SUPA_ENV="$ROOT/supabase/.env"
mkdir -p "$ROOT/supabase"

cat > "$SUPA_ENV" <<EOF
# AUTO-GENERATED by scripts/sync-secrets.sh from .env. Do not edit by hand.
# Run \`./scripts/sync-secrets.sh\` after changing .env.

# Supabase (Edge Functions get URL/keys via the runtime, but locally we surface them too)
SUPABASE_URL=${SUPABASE_URL:-}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}

# OpenAI
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL:-gpt-4o-mini}
OPENAI_EMBED_MODEL=${OPENAI_EMBED_MODEL:-text-embedding-3-small}

# APNs (used by notify-fanout)
APNS_KEY_ID=${APNS_KEY_ID:-}
APNS_TEAM_ID=${APNS_TEAM_ID:-}
APNS_BUNDLE_ID=${APNS_BUNDLE_ID:-}
APNS_PRIVATE_KEY_BASE64=${APNS_PRIVATE_KEY_BASE64:-}
APNS_ENVIRONMENT=${APNS_ENVIRONMENT:-sandbox}
EOF

echo "✓ wrote $SUPA_ENV"

cat <<EOF

Next steps:
  1. Regenerate the Xcode project so xcconfig changes get picked up:
       xcodegen generate
  2. Rebuild the app:
       xcodebuild -project Lumen.xcodeproj -scheme Lumen \\
         -destination 'platform=iOS Simulator,name=iPhone 17 Pro' build \\
         CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=YES | xcbeautify
  3. (If using Edge Functions) restart Supabase functions:
       supabase functions serve --env-file ./supabase/.env
  4. (Production) push secrets to Supabase:
       supabase secrets set --env-file ./supabase/.env
EOF
